### ISSUE TITLE
not work for this example

### ISSUE THREAD

**Issue by yuessir** [raminrahimzada/cConsole#1]
using:

var srcFolderName=Console.ReadLine();
AskQuestion($"Path is :{srcFolderName:red} ??") 

public static string AskQuestion(string question)
{
        CConsole.WriteLine($"{question}");
}

**Comment by raminrahimzada** [comment]
it is bcz you turn ```FormattableString```  into ```string``` by accepting ```string``` as an argument,
```CConsole``` actually needs ```FormattableString```  itself in order to process

You can try this one
```cs
... AskQuestion(FormattableString question)
{
       CConsole.WriteLine(question);
}
```

**Comment by yuessir** [comment]
In certain situations, the modification of a method's signature is not something that can be easily changed.

**Comment by raminrahimzada** [comment]
I understand you, but the purpose of this class is not to parse colored sub-parts from `string`.
 It is more complicated to parse from `string` like `"Your path is {path:red}"`  rather than `FormattableString` like  `$"Your path is {path:red}"` 
And this class was not supposed to do that.
